--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AID-LEARNING/php-amqplib-pmmp
build-by-default: true
projects:
  php-amqplib-pmmp:
    path: "PhpAmqpLib"
    model: virion
    type: library
...
